[project]
name = "nids-mlops-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Muskan Kumar", email = "muskankumar952593@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
nids-mlops-pipeline = "nids_mlops_pipeline:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
